### ISSUE TITLE
Image Ratio etc (4:3)

### ISSUE THREAD

**Issue by enkhtulga** [rossturner/HTML5-ImageUploader#20]
First of all, thank you for your awesome vue plugin. Is it possible to set image ratio etc (4:3), (1:1)?

**Comment by rossturner** [comment]
Thanks, though it's really a vanilla bunch of Javascript, not a Vue plugin in any way. 

Setting the image ratio would be a function of cropping the source or target image rather than just resizing. Currently only scaling an image is supported, but I'm sure the code could be extended to specify an image ratio and then calculate the bounds of the image to resize from instead.
